module.exports.ipLocation = require('./iplocation.js')
module.exports.myIp = require('./myip.js')
module.exports.whois = require('./whois.js')
module.exports.whoisV2 = require('./whoisV2.js')
module.exports.hostToIp = require('./hosttoip.js')